# ---- Build Stage ----
FROM gradle:8.4-jdk17 AS build

# 1. 빌드 시 전달받을 인자 정의
ARG USERNAME
ARG TOKEN

# 2. 환경 변수로 변환 (필요 시)
ENV GPR_USER=$USERNAME
ENV GPR_KEY=$TOKEN

WORKDIR /app
COPY . .

# 3. Gradle 빌드시 전달
RUN ./gradlew bootJar -Pgpr.user=$GPR_USER -Pgpr.key=$GPR_KEY --build-cache

# ---- Run Stage ----
FROM eclipse-temurin:17-jre

WORKDIR /app

COPY --from=build /app/build/libs/*.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]
