server:
  port: 8080

spring:
  application:
    name: order-service

# inventory-service의 내부 Docker 네트워크 기준 주소
inventory:
  url: http://inventory-service:8080

# 로그 레벨 설정 (선택)
logging:
  level:
    root: INFO
